services:

  redis:
    container_name: redis
    image: redis:latest
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: postgres
    image: postgres:latest
    deploy:
      replicas: 1
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db53" ]
      interval: 5s
      timeout: 5s
      retries: 5
