"""Initial migration

Revision ID: 93273e3fa17f
Revises: 9b551a10dd32
Create Date: 2024-08-20 16:48:16.184355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93273e3fa17f'
down_revision: Union[str, None] = '9b551a10dd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('all_', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_column('all_', 'user_name')
    op.drop_column('all_', 'user_host')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_', sa.Column('user_host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('all_', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('all_', 'user_id')
    op.drop_table('test_table')
    # ### end Alembic commands ###
