# Generated by Django 5.1 on 2024-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('item_id', models.BigIntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, null=True)),
                ('url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_',
                'managed': False,
            },
        ),
    ]
